import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LayoutProps = { children: React.ReactNode };
export default function Layout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
